language: node_js
node_js:
  - "6"

before_script:
  - sudo apt-get install postgresql-server-dev-all
  - sudo apt-get install postgresql-common

after_script: NODE_ENV=test lab --coverage-exclude static -r lcov | ./node_modules/.bin/coveralls
